# Generated by Django 5.1.2 on 2025-02-04 20:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.CharField(default='', max_length=255)),
                ('event_types', models.CharField(choices=[('club_matches', 'Club matches schedule'), ('club_training', 'Club training sessions schedule'), ('agm', 'Annual General Meeting'), ('trial_selection', 'Trial selection'), ('promotion', 'Promotion')], max_length=50)),
                ('event_date_start', models.DateTimeField()),
                ('event_date_end', models.DateTimeField()),
                ('location', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('event_img', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_tier', models.BigAutoField(primary_key=True, serialize=False)),
                ('membership_name', models.CharField(max_length=255)),
                ('cashback_rates', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_rates', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_desc', models.CharField(max_length=255)),
                ('item_qty', models.BigIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_rates', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('item_img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('member_email', models.EmailField(max_length=255, unique=True)),
                ('cashback_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='api.cartitems')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
