# Generated by Django 5.1.2 on 2024-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image_url',
            field=models.URLField(),
        ),
    ]
