# Generated by Django 5.1.2 on 2025-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productgroup_store_size_store_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='associated_items',
            field=models.ManyToManyField(blank=True, related_name='associations', to='api.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.CharField(default='NIL', max_length=10),
        ),
    ]
