# Generated by Django 5.1.2 on 2025-02-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_associated_items_alter_store_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='associated_items',
        ),
        migrations.AddField(
            model_name='store',
            name='associated_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productgroup'),
        ),
    ]
