# Generated by Django 5.1.2 on 2024-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_storeimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='store',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='store_images/'),
        ),
    ]
