# Generated by Django 5.1.2 on 2024-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_storeimage_image_url_store_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to='store_images/'),
        ),
    ]
