# Generated by Django 5.1.2 on 2025-02-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_store_associated_items_store_associated_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='associated_items',
        ),
    ]
