# Generated by Django 5.1.2 on 2024-11-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_name', models.CharField(max_length=50, unique=True)),
                ('cashback_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_rates', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='cashback',
            field=models.DecimalField(db_column='cashback_point_earned', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='cashback_expiry',
            field=models.DateTimeField(blank=True, db_column='expiration_date', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(db_column='member_email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='membership_tier',
            field=models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, to='api.membership'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_tier',
            field=models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, to='api.membership'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
