# Generated by Django 5.1.2 on 2025-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_store_associated_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
