# Generated by Django 5.1.2 on 2024-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_membership_role_alter_member_cashback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='membership_tier',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_tier',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Admin', 'Admin')], default='Bronze', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='cashback_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
