# Generated by Django 5.1.2 on 2025-01-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_storeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to='store_images'),
        ),
    ]
