# Generated by Django 5.1.2 on 2025-01-09 08:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_storeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
