# Generated by Django 5.1.2 on 2025-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_storeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_discounts',
            field=models.BooleanField(default=False),
        ),
    ]
