# Generated by Django 5.1.2 on 2025-01-09 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_store_has_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
