# Generated by Django 5.1.2 on 2025-01-11 19:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_store_has_discounts_store_item_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_img',
            field=cloudinary.models.CloudinaryField(default='backend/store_images/No_Image_Available.jpg', max_length=255, verbose_name='image'),
        ),
    ]
