# Generated by Django 5.1.2 on 2025-01-11 20:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_store_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
