# Generated by Django 5.1.2 on 2025-01-11 22:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_store_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
