# Generated by Django 5.1.2 on 2025-01-12 19:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_store_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.CharField(choices=[('club_matches', 'Club matches schedule'), ('club_training', 'Club training sessions schedule'), ('agm', 'Annual General Meeting'), ('trial_selection', 'Trial selection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
