# Generated by Django 5.1.2 on 2025-01-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.CharField(choices=[('club_matches', 'Club matches schedule'), ('club_training', 'Club training sessions schedule'), ('agm', 'Annual General Meeting'), ('trial_selection', 'Trial selection'), ('promotion', 'Promotion')], max_length=50),
        ),
    ]
