# Generated by Django 5.1.2 on 2025-01-23 12:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
